export const leadData = [
  {
    name: "Aaryan",
    desig: "Vice President",
    insta: "https://www.facebook.com/profile.php?id=100015547038499",
    linkedin: "https://www.linkedin.com/in/aaryan4200/",
    src: 'https://res.cloudinary.com/dcwqsevti/image/upload/v1694601616/ECS%20PHoto%20members/aaryan.jpg',
  },
  {
    name: "Nishtha Baruah",
    desig: "President",
    insta: "https://www.facebook.com/nistha.baruah.58",
    linkedin: "https://www.linkedin.com/in/nistha-baruah-201abb212/",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601616/ECS%20PHoto%20members/nistha.jpg",
  }
];
export const senData = [
   {
    name: "Aryadeep Gogoi",
    desig: "General Secretary",
    insta: "https://www.facebook.com/profile.php?id=100076109862434",
    linkedin: "https://www.linkedin.com/in/aryadeep-gogoi-696609236",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694603003/ECS%20PHoto%20members/aryadeep_pugod1.jpg",
  },
  {
    name: "Rohan Jha",
    desig: "Technical Head",
    insta: "https://www.facebook.com/profile.php?id=100010061770737",
    linkedin: "https://www.linkedin.com/in/rohan-jha-ab635322b/",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601618/ECS%20PHoto%20members/rohan.jpg",
  },
  {
    name: "Ananya Chetia",
    desig: "Literary and PR Head",
    insta: "https://www.facebook.com/ananya.chetia.10",
    linkedin: "https://www.linkedin.com/mwlite/in/ananya-chetia-a06ab6223",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601617/ECS%20PHoto%20members/ananya.jpg",
  },
    {
    name: "Priyambada Hazarika",
    desig: "Design Head",
    insta: "https://www.facebook.com/profile.php?id=100076411391244",
    linkedin: "https://www.linkedin.com/in/priyambada-hazarika-423237241",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694603904/ECS%20PHoto%20members/priyambada.jpg",
  },
   {
    name: "Vishnu Padmakumar",
    desig: "Treasurer",
    insta: "https://www.facebook.com/profile.php?id=100075797247014&mibextid=ZbWKwL",
    linkedin: "https://www.linkedin.com/in/vishnu-padmakumar-8515ba22a",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601617/ECS%20PHoto%20members/vishnu.jpg",
  },
  {
    name: "Vansh Kumar Poddar",
    desig: "Senior Executive",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601618/ECS%20PHoto%20members/Vansh_formal_h4fw03.jpg",
  },
  {
    name: "Amarjeet Kumar Chaurasia",
    desig: "Senior Executive",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601614/ECS%20PHoto%20members/amarjeet.jpg",
  },
];
export const junData = [
  {
    name: "Satyam Das",
    desig: "Junior Executive Member",
    insta: "",
    linkedin: "
      ",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601615/ECS%20PHoto%20members/satyam.jpg",
  },
  {
    name: "Abhiroop Bahera",
    desig: "Junior Executive Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601617/ECS%20PHoto%20members/abhiroop.jpg",
  },
  {
    name: "Abhipsa Banik",
    desig: "Junior Executive Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601616/ECS%20PHoto%20members/abhipsa.jpg",
  },
  {
    name: "Priyam Sogani",
    desig: "Junior Executive Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601618/ECS%20PHoto%20members/priyam.jpg",
  },
  {
    name: "Abdul Ijaj Ahmed",
    desig: "Junior Design Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601615/ECS%20PHoto%20members/ijaj.jpg",
  },
  {
    name: "Parismita Malakar",
    desig: "Junior Design Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601616/ECS%20PHoto%20members/parismita.jpg",
  },
  {
    name: "Jaruplvath Uday Karthik",
    desig: "Junior Design Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601621/ECS%20PHoto%20members/uday.jpg",
  },
  {
    name: "Aditi Goel",
    desig: "Junior Design Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601614/ECS%20PHoto%20members/aditi.jpg",
  },
  {
    name: "Annesha Dey",
    desig: "Junior Literary Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601617/ECS%20PHoto%20members/annesha.jpg",
  },
  {
    name: "Tripti Golcha",
    desig: "Junior Literary Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601618/ECS%20PHoto%20members/tripti.jpg",
  },
  {
    name: "Pallav Sharma",
    desig: "Junior Literary Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601617/ECS%20PHoto%20members/PallavSharmaCrpd3_shnygq.jpg",
  },
  {
    name: "Chetan Singh",
    desig: "Junior Literary Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601618/ECS%20PHoto%20members/chetan.jpg",
  },
  {
    name: "Pragyan Das",
    desig: "Junior Technical Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601616/ECS%20PHoto%20members/pragyan.jpg",
  },
  {
    name: "Jagatjyoti Deb",
    desig: "Junior Technical Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601615/ECS%20PHoto%20members/jagat.jpg",
  },
  {
    name: "Barnil Sarma",
    desig: "Junior Technical Member",
    insta: "",
    linkedin: "",
    src: "https://res.cloudinary.com/dcwqsevti/image/upload/v1694601618/ECS%20PHoto%20members/barnil.jpg",
  },
];
